services:
  - type: web
    name: VamToWkgConverter
    runtime: docker
    repo: https://github.com/lukegjpotter/VamToWkgConverter
    dockerContext: .
    dockerfilePath: Dockerfile
    region: frankfurt
    plan: free
    healthCheckPath: /health
    numInstances: 1
    autoDeploy: false
version: "1"